[package]
name = "burrito"
version = "0.0.1"
authors = ["Madison McGaffin <greyhill@gmail.com>"]
build = "build.rs"

[lib]
name = "burrito"
path = "src/lib.rs"
crate-type = ["rlib"]

[dependencies.libc]
libc="*"
